### ISSUE TITLE
Compilation error in `menu_coop.qc`

### ISSUE THREAD

**Issue by pluiedev** [nzp-team/quakec#93]
I'm in no way a QuakeC expert, but I really have no idea why it's interpreting it as a type
Very likely caused by https://github.com/nzp-team/quakec/commit/8c86b48547cdc2cd813850ecc1aab5f08208cd12

Tested both with upstream & forked FTEQCC

```console
nzp-quakec> progs/../source/menu/menu_coop.qc:292: macro NEXTBUTTON_FUNC is defined here
nzp-quakec> at global scope,
nzp-quakec> progs/../source/menu/menu_coop.qc:313:NEXTBUTTON_FUNC:2: error: "NEXTBUTTON_FUNC" is not a type
nzp-quakec> progs/../source/menu/menu_coop.qc:292: macro NEXTBUTTON_FUNC is defined here
nzp-quakec> progs/../source/menu/menu_coop.qc:314:NEXTBUTTON_FUNC:2: error: "NEXTBUTTON_FUNC" is not a type
nzp-quakec> progs/../source/menu/menu_coop.qc:292: macro NEXTBUTTON_FUNC is defined here
nzp-quakec> progs/../source/menu/menu_coop.qc:315:NEXTBUTTON_FUNC:2: error: "NEXTBUTTON_FUNC" is not a type
nzp-quakec> progs/../source/menu/menu_coop.qc:292: macro NEXTBUTTON_FUNC is defined here
nzp-quakec> progs/../source/menu/menu_coop.qc:316:NEXTBUTTON_FUNC:2: error: "NEXTBUTTON_FUNC" is not a type
nzp-quakec> progs/../source/menu/menu_coop.qc:320: macro PREVBUTTON_FUNC is defined here
nzp-quakec> progs/../source/menu/menu_coop.qc:341:PREVBUTTON_FUNC:2: error: "PREVBUTTON_FUNC" is not a type
nzp-quakec> progs/../source/menu/menu_coop.qc:320: macro PREVBUTTON_FUNC is defined here
nzp-quakec> progs/../source/menu/menu_coop.qc:342:PREVBUTTON_FUNC:2: error: "PREVBUTTON_FUNC" is not a type
nzp-quakec> progs/../source/menu/menu_coop.qc:320: macro PREVBUTTON_FUNC is defined here
nzp-quakec> progs/../source/menu/menu_coop.qc:343:PREVBUTTON_FUNC:2: error: "PREVBUTTON_FUNC" is not a type
nzp-quakec> progs/../source/menu/menu_coop.qc:320: macro PREVBUTTON_FUNC is defined here
nzp-quakec> progs/../source/menu/menu_coop.qc:344:PREVBUTTON_FUNC:2: error: "PREVBUTTON_FUNC" is not a type
```

**Comment by MotoLegacy** [comment]
The CI builds pass and I can't reproduce this locally. Can you provide insight as to your workflow and environment?

**Comment by pluiedev** [comment]
It's actually kind of an unusual environment — I've packaged NZ:P in [Nixpkgs](https://github.com/pluiedev/nixpkgs/blob/push-mptxqtrsyrvz/pkgs/by-name/nz/nzportable-quakec/package.nix) and due to a bootstrapping issue I opted to use upstream's FTEQCC to compile the QuakeC files. (The included Linux binaries don't work as they need runtime dependency patches)

I looked at nzp-team/fteqw and I don't see any major differences compared to upstream, at least inside qclib, so I really am curious as to what's happening here

**Comment by MotoLegacy** [comment]
https://github.com/nzp-team/quakec/pull/97
